pet/pet/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pet_vet.urls',)),
    path('shop/', include('shop.urls',))


]

pet/pet_vet/urls.py
from django.urls import path
from .views import index, services, contacts, about, appointment

app_name = 'pet_vet_app'

urlpatterns = [
    path('', index, name='index'),

    path('services/', services, name='services'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('appointment', appointment, name='appointment'),
]

pet/shop/urls.py
from django.urls import path
from .views import index
app_name = 'shop_app'

urlpatterns = [
    path('', index, name='index')
]

pet/pet_vet/models.py
from django.db import models


class Appointment(models.Model):
    client_name = models.CharField(max_length=150, verbose_name='Клиент')
    email = models.EmailField(max_length=150, )
    phone_number = models.CharField(max_length=100, verbose_name='Номер телефона')
    pet_type = models.CharField(max_length=150, verbose_name='Животное')
    date = models.DateField(verbose_name='День приёма')

    class Meta:
        verbose_name = 'Приём'
        verbose_name_plural = 'Приёмы'


class Animals(models.Model):
    types = models.CharField(max_length=150, verbose_name='Вид')

    class Meta:
        verbose_name = 'Животное'
        verbose_name_plural = 'Животные'

    def __str__(self):
        return self.types

pet/shop/models.py
from django.db import models

# Create your models here.

pet/pet_vet/views.py
from django.shortcuts import render, HttpResponse
from .models import Appointment, Animals


def index(request):
    return render(request, 'pet_vet/index.html')


def services(request):
    return render(request, 'pet_vet/services.html')


def appointment(request):
    if request.method == 'POST':
        client_name = request.POST.get('client_name')
        email = request.POST.get('client_email')
        phone_number = request.POST.get('phone_number')
        pet_type = request.POST.get('pet_type')
        date = request.POST.get('date')
        item = Appointment(client_name=client_name, email=email, phone_number=phone_number, pet_type=pet_type,
                           date=date,)
        item.save()
        return render(request, 'pet_vet/doctor_appointment.html')
    else:
        animals = Animals.objects.all()
        context = {'animals': animals}
        return render(request, 'pet_vet/doctor_appointment.html', context=context)


def shop(request):
    return render(request, 'pet_vet/shop.html')


def contacts(request):
    return render(request, 'pet_vet/contacts.html')


def about(request):
    return render(request, 'pet_vet/about.html')

pet/shop/views.py
from django.shortcuts import render, HttpResponse


# Create your views here.

def index(request):
    return HttpResponse('<h1>Магазин</h1>')

pet/pet_vet/templates/pet_vet/about.html
{% extends 'pet_vet/base.html' %}}

pet/pet_vet/templates/pet_vet/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/service-styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/lumen/bootstrap.min.css" integrity="sha384-GzaBcW6yPIfhF+6VpKMjxbTx6tvR/yRd/yJub90CqoIn2Tz4rRXlSpTFYMKHCifX" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <title>Клиника</title>
</head>
<body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pet_vet_app:index' %}">Усы, лапы и хвост</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'pet_vet_app:index' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'pet_vet_app:services' %}">Услуги</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'shop_app:index' %}">Магазин</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'pet_vet_app:appointment' %}">Записаться на приём</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">Обратный звонок</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'pet_vet_app:contacts' %}">Контакты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'pet_vet_app:about' %}">О нас</a>
                </li>

          </ul>
        </div>
      </div>
    </nav>
    </header>
    {% block content %}
    {% endblock %}
</body>
</html>

pet/pet_vet/templates/pet_vet/contacts.html
{% extends 'pet_vet/base.html' %}

pet/pet_vet/templates/pet_vet/doctor_appointment.html
{% extends 'pet_vet/base.html' %}


{% block content %}
<form method="post" action="{% url 'pet_vet_app:appointment' %}">
    {% csrf_token %}
    <table style="margin:auto; width:600px;">
        <tr>
            <td><label class="form-label mt-4">Имя</label></td>
            <td><label class="form-label mt-4">Почта</label></td>
        </tr>
        <tr>
            <td><input type="text" class="form-control" name="client_name" required></td>
            <td><input type="text" class="form-control" name="client_email" required></td>
        </tr>
        <tr>
            <td><label class="form-label mt-4">Номер телефона</label></td>
            <td><label class="form-label mt-4">Животное</label></td>
        </tr>
        <tr>
            <td><input type="tel"  name='phone_number' class="form-control" pattern="+7-[0-9]{3}-[0-9]{3}-[0-9]{4}"
            placeholder="В формате +7-xxx-xxx-xxxx" required></td>
            <td>
                <select class="select" style="width:100%" name="pet_type" required>
                    {% for animal in animals %}
                        <option>{{ animal }}</option>
                    {% endfor %}
                    <option value="another">Другое</option>
                </select>

            </td>
        </tr>
        <tr>
            <td>
                <label class="form-label mt-4" >День приёма</label>
            </td>
        </tr>
        <tr>
            <td>
                <input type="date" name="date" required>
            </td>
        </tr>
        <tr style="margin-top:auto;">
            <td>
                <input type="submit" class="btn btn-primary" value="Записаться" style="margin-top:20px;">
            </td>
        </tr>
    </table>
</form>
{% endblock %}

pet/pet_vet/templates/pet_vet/index.html
{% extends 'pet_vet/base.html' %}
{% load static %}

{% block content %}
    <div class="row">

        <div class="col-lg-4 presentation" >
            <h2>Усы, лапы и хвост</h2>
            <p>крупнейший ветеринарный центр в Казахстане</p>
            <p><strong>233 413+</strong> спасенных жизней за 10 лет работы</p>
            <p>ЦВМ оснащен лабораторией и оборудованием для быстрой диагностики и лечения животных.
                <strong>Полноценное обследование животного невозможно без лабораторных гематологических
                и биохимических анализаторов, рентгена, УЗИ, устройств функциональной диагностики.</strong></p>

            <ul>
                <li>Лучшие втеринарные врачи страны</li>
                <li>Сложнейшие операции</li>
                <li>Узкие специалисты</li>
                <li>Точная диагностика</li>
                <li>Собственная клинико-диагностическа лаборатория</li>
            </ul>
            <p>Врачи в ЦВМ работают в условиях диагностической определенности и практикуют новейшие методики лечения
                повышая эффективность и качество оказываемой помощи.</p>
        </div>

        <div class="col-lg-4">
            <img src="{% static 'images/pet_background.jpg' %}" alt="" width="500" height="500">
        </div>

    </div>

{% endblock %}

pet/pet_vet/templates/pet_vet/services.html
{% extends 'pet_vet/base.html' %}

{% block content %}

    <table class="service-cards">
        <tr>
            <th>
                <div class="card text-white bg-primary mb-3" style="max-width: 15rem;">
                  <div class="card-body">
                    <h4 class="card-title">Хирургия</h4>
                  </div>
                </div>
            <th>
            <th>
                <div class="card text-white bg-primary mb-3" style="max-width: 15rem;">
                  <div class="card-body">
                    <h4 class="card-title">Ортопедия</h4>
                  </div>
                </div>
            <th>
            <th>
                <div class="card text-white bg-primary mb-3" style="max-width: 15rem;">
                  <div class="card-body">
                    <h4 class="card-title">Эндохирургия</h4>
                  </div>
                </div>
            <th>
        </tr>
        <tr>
            <th>
                <div class="card text-white bg-primary mb-3" style="max-width: 15rem;">
                  <div class="card-body">
                    <h4 class="card-title">Чипирование</h4>
                  </div>
                </div>
            <th>
            <th>
                <div class="card text-white bg-primary mb-3" style="max-width: 15rem;">
                  <div class="card-body">
                    <h4 class="card-title">Стационар</h4>
                  </div>
                </div>
            <th>
            <th>
                <div class="card text-white bg-primary mb-3" style="max-width: 15rem;">
                  <div class="card-body">
                    <h4 class="card-title">Лаборатория</h4>
                  </div>
                </div>
            <th>
        </tr>

    </table>

{% endblock %}

pet/pet_vet/templates/pet_vet/shop.html
{% extends 'pet_vet/base.html' %}